"""Signal's native, dark desktop interface. Logo and meter are vector drawings."""
import tkinter as tk
from pathlib import Path
from tkinter import ttk

BG = "#0c1017"
CARD = "#141b25"
INPUT = "#1c2633"
LINE = "#283545"
TEXT = "#e9f0f7"
MUTED = "#93a5b9"
ACCENT = "#67e8c2"


class SignalUI:
    def build_ui(self):
        self.title("Signal — Audio into words")
        self.geometry("1120x850")
        self.minsize(1020, 760)
        self.configure(bg=BG)
        style = ttk.Style(self)
        style.theme_use("clam")
        style.configure("TFrame", background=BG)
        style.configure("Card.TFrame", background=CARD)
        style.configure("TLabel", background=CARD, foreground=TEXT, font=("Segoe UI", 10))
        style.configure("Muted.TLabel", foreground=MUTED)
        style.configure("TButton", background=INPUT, foreground=TEXT, borderwidth=0, padding=(12, 9), font=("Segoe UI", 10))
        style.map("TButton", background=[("active", LINE), ("disabled", CARD)], foreground=[("disabled", "#526176")])
        style.configure("Accent.TButton", background=ACCENT, foreground=BG, font=("Segoe UI", 10, "bold"))
        style.map("Accent.TButton", background=[("disabled", INPUT), ("active", "#a0f5dd")], foreground=[("disabled", MUTED)])
        style.configure("Stop.TButton", background="#55303b", foreground="#ffb1bf")
        style.map("Stop.TButton", background=[("active", "#70404c")])
        style.configure("TEntry", fieldbackground=INPUT, foreground=TEXT, insertcolor=TEXT, bordercolor=LINE, lightcolor=LINE, darkcolor=LINE, padding=8)
        style.configure("TCombobox", fieldbackground=INPUT, background=INPUT, foreground=TEXT, arrowcolor=MUTED, bordercolor=LINE, lightcolor=LINE, darkcolor=LINE, padding=7)
        style.map("TCombobox", fieldbackground=[("readonly", INPUT), ("disabled", CARD)], foreground=[("readonly", TEXT), ("disabled", MUTED)], selectbackground=[("readonly", INPUT)], selectforeground=[("readonly", TEXT)])
        style.configure("TCheckbutton", background=CARD, foreground=MUTED, font=("Segoe UI", 10), padding=4)
        style.map("TCheckbutton", background=[("active", CARD)], foreground=[("disabled", "#526176")])
        style.configure("Horizontal.TProgressbar", background=ACCENT, troughcolor=INPUT, bordercolor=BG, lightcolor=BG, darkcolor=BG, borderwidth=0, thickness=3)
        style.configure("Vertical.TScrollbar", background=LINE, troughcolor=CARD, arrowcolor=MUTED, bordercolor=CARD, lightcolor=LINE, darkcolor=LINE, borderwidth=0)
        style.map("Vertical.TScrollbar", background=[("active", MUTED), ("!active", LINE)])
        self.option_add("*TCombobox*Listbox.background", INPUT)
        self.option_add("*TCombobox*Listbox.foreground", TEXT)
        self.option_add("*TCombobox*Listbox.selectBackground", LINE)
        self.option_add("*TCombobox*Listbox.selectForeground", ACCENT)
        self.option_add("*TCombobox*Listbox.font", ("Segoe UI", 10))

        shell = ttk.Frame(self, padding=24)
        shell.pack(fill="both", expand=True)
        header = ttk.Frame(shell)
        header.pack(fill="x", pady=(0, 22))
        logo = tk.Canvas(header, width=44, height=44, bg=BG, highlightthickness=0)
        logo.pack(side="left", padx=(0, 12))
        for x, height in zip((8, 15, 22, 29, 36), (12, 24, 36, 24, 12)):
            logo.create_line(x, 22-height/2, x, 22+height/2, fill=ACCENT, width=4, capstyle="round")
        self.logo_image = tk.PhotoImage(width=48, height=48)
        self.logo_image.put(BG, to=(0, 0, 48, 48))
        for x, height in zip((8, 16, 24, 32, 40), (12, 24, 36, 24, 12)):
            self.logo_image.put(ACCENT, to=(x-2, 24-height//2, x+2, 24+height//2))
        self.iconphoto(True, self.logo_image)
        names = ttk.Frame(header)
        names.pack(side="left")
        tk.Label(names, text="SIGNAL", bg=BG, fg=TEXT, font=("Segoe UI", 20, "bold")).pack(anchor="w")
        tk.Label(names, text="Audio into words.", bg=BG, fg=MUTED, font=("Segoe UI", 10)).pack(anchor="w")
        self.library_button = ttk.Button(header, text="Open library ↗", command=self.open_library)
        self.library_button.pack(side="right")
        self.output_button = ttk.Button(header, text="Save location…", command=self.choose_output)
        self.output_button.pack(side="right", padx=(0, 8))
        tk.Label(header, text="●  LOCAL PROCESSING", bg=BG, fg=ACCENT, font=("Segoe UI", 9, "bold")).pack(side="right", padx=22)

        session = ttk.Frame(shell, style="Card.TFrame", padding=(14, 10))
        session.pack(fill="x", pady=(0, 14))
        session_row = ttk.Frame(session, style="Card.TFrame")
        session_row.pack(fill="x")
        ttk.Label(session_row, text="Session name", style="Muted.TLabel").pack(side="left", padx=(0, 12))
        self.session_entry = ttk.Entry(session_row, textvariable=self.session_name, width=35)
        self.session_entry.pack(side="left", fill="x", expand=True, padx=(0, 12))
        self.session_open_button = ttk.Button(session_row, text="Open session folder ↗", command=self.open_session, state="disabled")
        self.session_open_button.pack(side="right")
        ttk.Label(session, textvariable=self.session_path, style="Muted.TLabel", font=("Segoe UI", 9), wraplength=990).pack(anchor="w", pady=(6, 0))
        self.session_name.trace_add("write", self.update_session_preview)

        body = ttk.Frame(shell)
        body.pack(fill="both", expand=True)
        body.columnconfigure(0, weight=0, minsize=370)
        body.columnconfigure(1, weight=1)
        body.rowconfigure(0, weight=1)
        left_shell = ttk.Frame(body, style="Card.TFrame")
        left_shell.grid(row=0, column=0, sticky="nsew", padx=(0, 16))
        left_canvas = tk.Canvas(left_shell, width=370, bg=CARD, highlightthickness=0)
        left_scroll = ttk.Scrollbar(left_shell, orient="vertical", command=left_canvas.yview)
        left_scroll.pack(side="right", fill="y")
        left_canvas.pack(side="left", fill="both", expand=True)
        left_canvas.configure(yscrollcommand=left_scroll.set)
        left = ttk.Frame(left_canvas, style="Card.TFrame", padding=20)
        left_window = left_canvas.create_window(0, 0, window=left, anchor="nw", width=370)
        left.bind("<Configure>", lambda e: left_canvas.configure(scrollregion=left_canvas.bbox("all")))
        left_canvas.bind("<Configure>", lambda e: left_canvas.itemconfigure(left_window, width=e.width))
        left.columnconfigure(0, weight=1)
        ttk.Label(left, text="01 / SOURCE", style="Muted.TLabel", font=("Segoe UI", 9, "bold")).grid(row=0, column=0, sticky="w", pady=(0, 14))
        tabs = ttk.Frame(left, style="Card.TFrame")
        tabs.grid(row=1, column=0, sticky="ew", pady=(0, 18))
        self.capture_tab = ttk.Button(tabs, text="Record audio", command=lambda: self.set_mode("capture"))
        self.capture_tab.pack(side="left", fill="x", expand=True, padx=(0, 5))
        self.file_tab = ttk.Button(tabs, text="Import file", command=lambda: self.set_mode("file"))
        self.file_tab.pack(side="left", fill="x", expand=True)

        self.capture_panel = ttk.Frame(left, style="Card.TFrame")
        self.capture_panel.grid(row=2, column=0, sticky="ew")
        self.source_box = ttk.Combobox(self.capture_panel, textvariable=self.source_name, values=list(self.sources), state="readonly")
        self.source_box.pack(fill="x", pady=(0, 10))
        self.source_box.bind("<<ComboboxSelected>>", self.source_changed)
        self.device_section = ttk.Frame(self.capture_panel, style="Card.TFrame")
        self.device_section.pack(fill="x")
        ttk.Label(self.device_section, text="Computer playback", style="Muted.TLabel").pack(anchor="w")
        device_row = ttk.Frame(self.device_section, style="Card.TFrame")
        device_row.pack(fill="x", pady=(4, 8))
        self.device_box = ttk.Combobox(device_row, textvariable=self.device_name, state="readonly", width=22)
        self.device_box.pack(side="left", fill="x", expand=True)
        self.refresh_button = ttk.Button(device_row, text="↻", width=3, command=self.refresh_devices)
        self.refresh_button.pack(side="right", padx=(6, 0))
        self.microphone_section = ttk.Frame(self.capture_panel, style="Card.TFrame")
        self.microphone_section.pack(fill="x")
        mic_row = ttk.Frame(self.microphone_section, style="Card.TFrame")
        mic_row.pack(fill="x")
        ttk.Label(mic_row, text="Microphone input", style="Muted.TLabel").pack(side="left")
        self.mic_refresh_button = ttk.Button(mic_row, text="↻", width=3, command=self.refresh_devices)
        self.mic_refresh_button.pack(side="right")
        self.microphone_box = ttk.Combobox(self.microphone_section, textvariable=self.microphone_name, state="readonly")
        self.microphone_box.pack(fill="x", pady=(4, 8))
        self.timer_label = ttk.Label(self.capture_panel, text="00:00:00", font=("Consolas", 25))
        self.timer_label.pack(pady=(4, 2))
        self.capture_hint = ttk.Label(self.capture_panel, text="READY TO CAPTURE", style="Muted.TLabel", font=("Segoe UI", 9, "bold"))
        self.capture_hint.pack()
        self.meter = tk.Canvas(self.capture_panel, height=48, bg=CARD, highlightthickness=0)
        self.meter.pack(fill="x", pady=(6, 8))
        self.meter.bind("<Configure>", lambda e: self.draw_meter())
        self.meter_values = [0] * 44
        self.record_button = ttk.Button(self.capture_panel, text="●  Start recording", style="Accent.TButton", command=self.start_recording)
        self.record_button.pack(fill="x")
        self.stop_button = ttk.Button(self.capture_panel, text="■  Stop & transcribe", style="Stop.TButton", command=self.stop_recording)
        self.auto_check = ttk.Checkbutton(self.capture_panel, text="Transcribe when recording stops", variable=self.auto_transcribe, command=self.save_settings)
        self.auto_check.pack(anchor="w", pady=(9, 5))
        self.source_hint = ttk.Label(self.capture_panel, text="", style="Muted.TLabel", font=("Segoe UI", 9), wraplength=320)
        self.source_hint.pack(anchor="w")

        self.file_panel = ttk.Frame(left, style="Card.TFrame")
        self.file_panel.grid(row=2, column=0, sticky="ew")
        ttk.Label(self.file_panel, text="Bring your own audio", font=("Segoe UI", 17, "bold")).pack(anchor="w", pady=(8, 8))
        ttk.Label(self.file_panel, text="Recordings, interviews, lectures, or videos.\nMP3 · WAV · M4A · MP4 and more", style="Muted.TLabel").pack(anchor="w", pady=(0, 16))
        self.file_label = ttk.Label(self.file_panel, text="No file selected", wraplength=320)
        self.file_label.pack(anchor="w", pady=(0, 10))
        self.file_button = ttk.Button(self.file_panel, text="Choose audio or video…", command=self.choose_audio)
        self.file_button.pack(fill="x", pady=(0, 12))
        self.start_button = ttk.Button(self.file_panel, text="Transcribe file →", style="Accent.TButton", command=self.start)
        self.start_button.pack(fill="x")
        ttk.Label(self.file_panel, text="Your source file is kept unchanged.", style="Muted.TLabel").pack(anchor="w", pady=12)

        options = ttk.Frame(left, style="Card.TFrame")
        options.grid(row=3, column=0, sticky="ew", pady=(18, 0))
        ttk.Label(options, text="02 / QUALITY & LANGUAGE", style="Muted.TLabel", font=("Segoe UI", 9, "bold")).pack(anchor="w", pady=(0, 10))
        option_row = ttk.Frame(options, style="Card.TFrame")
        option_row.pack(fill="x")
        self.quality_box = ttk.Combobox(option_row, textvariable=self.quality_name, values=list(self.qualities), state="readonly", width=17)
        self.quality_box.pack(side="left", fill="x", expand=True, padx=(0, 8))
        self.quality_box.bind("<<ComboboxSelected>>", self.quality_changed)
        self.language_box = ttk.Combobox(option_row, textvariable=self.language, values=["Auto detect", "en", "fr", "es", "de", "it", "pt", "nl", "ja", "zh"], width=10)
        self.language_box.pack(side="right")
        self.quality_hint = ttk.Label(options, text="Balanced speed and accuracy", style="Muted.TLabel", font=("Segoe UI", 9))
        self.quality_hint.pack(anchor="w", pady=(7, 12))
        self.output_label = ttk.Label(options, text="", style="Muted.TLabel", wraplength=320, font=("Segoe UI", 9))
        self.controls = [(self.quality_box, "readonly"), (self.language_box, "normal"), (self.output_button, "normal"), (self.file_button, "normal"), (self.auto_check, "normal"), (self.capture_tab, "normal"), (self.file_tab, "normal"), (self.source_box, "readonly"), (self.mic_refresh_button, "normal")]
        self.controls.append((self.session_entry, "normal"))

        right = ttk.Frame(body, style="Card.TFrame", padding=20)
        right.grid(row=0, column=1, sticky="nsew")
        transcript_header = ttk.Frame(right, style="Card.TFrame")
        transcript_header.pack(fill="x")
        ttk.Label(transcript_header, text="Transcript", font=("Segoe UI", 18, "bold")).pack(side="left")
        self.word_label = ttk.Label(transcript_header, text="0 words", style="Muted.TLabel")
        self.word_label.pack(side="right")
        recent_row = ttk.Frame(right, style="Card.TFrame")
        recent_row.pack(fill="x", pady=(14, 10))
        self.recent_box = ttk.Combobox(recent_row, textvariable=self.recent_name, state="readonly")
        self.recent_box.pack(fill="x")
        self.recent_box.bind("<<ComboboxSelected>>", self.load_recent)
        search_row = ttk.Frame(right, style="Card.TFrame")
        search_row.pack(fill="x", pady=(0, 12))
        ttk.Label(search_row, text="Search", style="Muted.TLabel").pack(side="left", padx=(0, 8))
        self.search_entry = ttk.Entry(search_row, textvariable=self.search_text)
        self.search_entry.pack(side="left", fill="x", expand=True, padx=(0, 8))
        self.search_entry.bind("<Return>", self.find_text)
        self.search_entry.bind("<FocusIn>", lambda e: self.status.set("Search transcript: enter a phrase and press Enter. Ctrl+F focuses search."))
        ttk.Button(search_row, text="Find next", command=self.find_text).pack(side="right")
        text_area = ttk.Frame(right, style="Card.TFrame")
        text_area.pack(fill="both", expand=True)
        self.preview = tk.Text(text_area, wrap="word", font=("Segoe UI", 12), relief="flat", bg=CARD, fg=TEXT, insertbackground=ACCENT, selectbackground="#31584f", padx=2, pady=8, spacing1=3, spacing3=7, highlightthickness=0, state="disabled", height=10, width=30)
        self.preview.pack(side="left", fill="both", expand=True)
        scrollbar = ttk.Scrollbar(text_area, orient="vertical", command=self.preview.yview)
        scrollbar.pack(side="right", fill="y")
        self.preview.configure(yscrollcommand=scrollbar.set)
        self.preview.tag_configure("match", background=ACCENT, foreground=BG)
        self.empty_label = tk.Label(self.preview, text="Your next idea starts here.\n\nName a session, then record or import audio.\nAudio and text are saved together.", bg=CARD, fg=MUTED, font=("Segoe UI", 12), justify="center")
        self.empty_label.place(relx=.5, rely=.42, anchor="center")
        actions = ttk.Frame(right, style="Card.TFrame")
        actions.pack(fill="x", pady=(16, 0))
        self.copy_button = ttk.Button(actions, text="Copy text", command=self.copy, state="disabled")
        self.copy_button.pack(side="left", padx=(0, 8))
        self.export_button = ttk.Button(actions, text="Save as…", command=self.export_text, state="disabled")
        self.export_button.pack(side="left")
        self.folder_button = ttk.Button(actions, text="Files ↗", command=self.open_results, state="disabled")
        self.folder_button.pack(side="right")
        self.progress = ttk.Progressbar(shell, maximum=100)
        self.progress.pack(fill="x", pady=(18, 10))
        footer = ttk.Frame(shell)
        footer.pack(fill="x")
        self.state_label = tk.Label(footer, text="● READY", bg=BG, fg=ACCENT, font=("Segoe UI", 9, "bold"))
        self.state_label.pack(side="left", padx=(0, 14))
        tk.Label(footer, textvariable=self.status, bg=BG, fg=MUTED, font=("Segoe UI", 9), anchor="w", wraplength=760, justify="left").pack(side="left", fill="x", expand=True)
        self.cancel_button = ttk.Button(footer, text="Cancel", command=self.cancel, state="disabled")
        self.cancel_button.pack(side="right")
        # Reserve the status area before allocating the resizable workspace.
        body.pack_forget()
        self.progress.pack_forget()
        footer.pack_forget()
        footer.pack(side="bottom", fill="x")
        self.progress.pack(side="bottom", fill="x", pady=(18, 10))
        body.pack(fill="both", expand=True)
        self.audio.trace_add("write", lambda *a: self.file_label.configure(text=Path(self.audio.get()).name or "No file selected"))
        self.bind("<Control-o>", lambda e: self.choose_audio() if not self.process and not self.recording_thread else None)
        self.bind("<Control-f>", lambda e: self.search_entry.focus_set())
        self.bind("<Control-Shift-C>", lambda e: self.copy())
        self.set_mode("capture")
        self.source_changed()
        self.update_output_label()
        self.quality_changed()
        self.after(10, self.dark_titlebar)

    def dark_titlebar(self):
        # Apply the OS's dark title-bar attribute to this app's own window.
        try:
            import ctypes
            get_parent = ctypes.windll.user32.GetParent
            get_parent.restype = ctypes.c_void_p
            handle = get_parent(ctypes.c_void_p(self.winfo_id()))
            enabled = ctypes.c_int(1)
            setter = ctypes.windll.dwmapi.DwmSetWindowAttribute
            setter(ctypes.c_void_p(handle), 20, ctypes.byref(enabled), 4)
            for attribute, color in ((35, 0x17100c), (36, 0xf7f0e9)):
                value = ctypes.c_uint(color)
                setter(ctypes.c_void_p(handle), attribute, ctypes.byref(value), 4)
        except (AttributeError, OSError):
            pass

    def set_mode(self, mode):
        self.mode = mode
        self.capture_panel.grid() if mode == "capture" else self.capture_panel.grid_remove()
        self.file_panel.grid() if mode == "file" else self.file_panel.grid_remove()
        self.capture_tab.configure(style="Accent.TButton" if mode == "capture" else "TButton")
        self.file_tab.configure(style="Accent.TButton" if mode == "file" else "TButton")

    def draw_meter(self, level=None):
        if level is not None:
            self.meter_values = self.meter_values[1:] + [level]
        self.meter.delete("all")
        width = max(self.meter.winfo_width(), 100)
        for i, value in enumerate(self.meter_values):
            height = max(3, min(40, (max(value, 0) / 100) ** .5 * 40))
            x = 4 + i * (width - 8) / len(self.meter_values)
            self.meter.create_line(x, 24-height/2, x, 24+height/2, width=3, fill=ACCENT if value > .1 else LINE, capstyle="round")
